name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'master' # Use the master channel for the latest updates

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Clear Pub Cache
        run: flutter pub cache clean

      - name: Validate Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Add .nojekyll
        run: echo > build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRECT_KEY_NAME }}
          publish_dir: build/web
          publish_branch: gh-pages