name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get install -y git curl unzip xz-utils libglu1-mesa

      - name: Clone Flutter Repository
        run: git clone https://github.com/flutter/flutter.git -b master $HOME/flutter

      - name: Add Flutter to PATH
        run: echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Doctor
        run: flutter doctor

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Validate Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Clear Pub Cache
        run: flutter pub cache clean

      - name: Install Flutter Dependencies
        run: flutter pub get


      - name: Make server_config.sh Executable
        run: chmod +x ./server_config.sh
      - name: Run Server Config Script
        run: bash ./server_config.sh

      - name: Build Web
        run: flutter build web --release

      - name: Add .nojekyll
        run: echo > build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRECT_KEY_NAME }}
          publish_dir: build/web
          publish_branch: gh-pages