name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'  # Use Dart SDK 3.5.0 or later

      - name: Clear Pub Cache
        run: flutter pub cache clean  # Optional: Clear any cached dependencies

      - name: Install Dependencies
        run: flutter pub get

      - name: Make server_config.sh Executable
        run: chmod +x ./server_config.sh

      - name: Run Server Config Script
        run: bash ./server_config.sh

      - name: Build Web
        run: flutter build web --release

      - name: Add .nojekyll
        run: echo > build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRECT_KEY_NAME }}
          publish_dir: build/web
          publish_branch: gh-pages